package:
  name: blp
  version: "0.0.2"

source:
  git_tag: master
  git_url: https://github.com/yowtzu/blp

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pandas
    - nose
    - blpapi

  run:
    - python
    - numpy
    - pandas
    - nose
    - blpapi

  # Python imports
  #imports:
  #  - pyinstrument

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/yowtzu/blp
  license: BSD License
  summary: "Bloomberg API Wrapper"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
